### ISSUE TITLE
Error: Cannot find module './phoneme-types'

### ISSUE THREAD

**Issue by factormystic** [jimkang/phonemenon#1]
```
$ node
> require('phonemenon')
Error: Cannot find module './phoneme-types'
```

How is this module supposed to be used?

**Comment by jimkang** [comment]
I just added a little more explanation:

https://github.com/jimkang/phonemenon/commit/674d6d5e2d0d7ebb39d3491972d6e4a40fdb5e8a

After you clone the repo, cd into it, and run `npm install`, you can run the scripts from there. The Makefile has several targets you can use to run the scripts in this repo.

**Comment by factormystic** [comment]
Alright, thanks
